<?php 
add_action( 'acf/include_fields', function() {
	if ( ! function_exists( 'acf_add_local_field_group' ) ) {
		return;
	}

	acf_add_local_field_group( array(
		'key' => 'group_647f4c86974b1',
		'title' => 'Store Information',
		'fields' => array(
			array(
				'key' => 'field_647f4c86ac956',
				'label' => 'Store Name',
				'name' => 'store_name',
				'aria-label' => '',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'maxlength' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
			),
			array(
				'key' => 'field_647f4ffbac957',
				'label' => 'Street Address',
				'name' => 'street_address',
				'aria-label' => '',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'maxlength' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
			),
			array(
				'key' => 'field_647f501aac958',
				'label' => 'Secondary Address',
				'name' => 'secondary_address',
				'aria-label' => '',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'maxlength' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
			),
			array(
				'key' => 'field_647f5136ac95b',
				'label' => 'Country',
				'name' => 'country',
				'aria-label' => '',
				'type' => 'select',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'Afghanistan' => 'Afghanistan',
					'Albania' => 'Albania',
					'Algeria' => 'Algeria',
					'Andorra' => 'Andorra',
					'Angola' => 'Angola',
					'Antigua & Deps' => 'Antigua & Deps',
					'Argentina' => 'Argentina',
					'Armenia' => 'Armenia',
					'Australia' => 'Australia',
					'Austria' => 'Austria',
					'Azerbaijan' => 'Azerbaijan',
					'Bahamas' => 'Bahamas',
					'Bahrain' => 'Bahrain',
					'Bangladesh' => 'Bangladesh',
					'Barbados' => 'Barbados',
					'Belarus' => 'Belarus',
					'Belgium' => 'Belgium',
					'Belize' => 'Belize',
					'Benin' => 'Benin',
					'Bhutan' => 'Bhutan',
					'Bolivia' => 'Bolivia',
					'Bosnia Herzegovina' => 'Bosnia Herzegovina',
					'Botswana' => 'Botswana',
					'Brazil' => 'Brazil',
					'Brunei' => 'Brunei',
					'Bulgaria' => 'Bulgaria',
					'Burkina' => 'Burkina',
					'Burundi' => 'Burundi',
					'Cambodia' => 'Cambodia',
					'Cameroon' => 'Cameroon',
					'Canada' => 'Canada',
					'Cape Verde' => 'Cape Verde',
					'Central African Rep' => 'Central African Rep',
					'Chad' => 'Chad',
					'Chile' => 'Chile',
					'China' => 'China',
					'Colombia' => 'Colombia',
					'Comoros' => 'Comoros',
					'Congo' => 'Congo',
					'Congo {Democratic Rep}' => 'Congo {Democratic Rep}',
					'Costa Rica' => 'Costa Rica',
					'Croatia' => 'Croatia',
					'Cuba' => 'Cuba',
					'Cyprus' => 'Cyprus',
					'Czech Republic' => 'Czech Republic',
					'Denmark' => 'Denmark',
					'Djibouti' => 'Djibouti',
					'Dominica' => 'Dominica',
					'Dominican Republic' => 'Dominican Republic',
					'East Timor' => 'East Timor',
					'Ecuador' => 'Ecuador',
					'Egypt' => 'Egypt',
					'El Salvador' => 'El Salvador',
					'Equatorial Guinea' => 'Equatorial Guinea',
					'Eritrea' => 'Eritrea',
					'Estonia' => 'Estonia',
					'Ethiopia' => 'Ethiopia',
					'Fiji' => 'Fiji',
					'Finland' => 'Finland',
					'France' => 'France',
					'Gabon' => 'Gabon',
					'Gambia' => 'Gambia',
					'Georgia' => 'Georgia',
					'Germany' => 'Germany',
					'Ghana' => 'Ghana',
					'Greece' => 'Greece',
					'Grenada' => 'Grenada',
					'Guatemala' => 'Guatemala',
					'Guinea' => 'Guinea',
					'Guinea-Bissau' => 'Guinea-Bissau',
					'Guyana' => 'Guyana',
					'Haiti' => 'Haiti',
					'Honduras' => 'Honduras',
					'Hungary' => 'Hungary',
					'Iceland' => 'Iceland',
					'India' => 'India',
					'Indonesia' => 'Indonesia',
					'Iran' => 'Iran',
					'Iraq' => 'Iraq',
					'Ireland {Republic}' => 'Ireland {Republic}',
					'Israel' => 'Israel',
					'Italy' => 'Italy',
					'Ivory Coast' => 'Ivory Coast',
					'Jamaica' => 'Jamaica',
					'Japan' => 'Japan',
					'Jordan' => 'Jordan',
					'Kazakhstan' => 'Kazakhstan',
					'Kenya' => 'Kenya',
					'Kiribati' => 'Kiribati',
					'Korea North' => 'Korea North',
					'Korea South' => 'Korea South',
					'Kosovo' => 'Kosovo',
					'Kuwait' => 'Kuwait',
					'Kyrgyzstan' => 'Kyrgyzstan',
					'Laos' => 'Laos',
					'Latvia' => 'Latvia',
					'Lebanon' => 'Lebanon',
					'Lesotho' => 'Lesotho',
					'Liberia' => 'Liberia',
					'Libya' => 'Libya',
					'Liechtenstein' => 'Liechtenstein',
					'Lithuania' => 'Lithuania',
					'Luxembourg' => 'Luxembourg',
					'Macedonia' => 'Macedonia',
					'Madagascar' => 'Madagascar',
					'Malawi' => 'Malawi',
					'Malaysia' => 'Malaysia',
					'Maldives' => 'Maldives',
					'Mali' => 'Mali',
					'Malta' => 'Malta',
					'Marshall Islands' => 'Marshall Islands',
					'Mauritania' => 'Mauritania',
					'Mauritius' => 'Mauritius',
					'Mexico' => 'Mexico',
					'Micronesia' => 'Micronesia',
					'Moldova' => 'Moldova',
					'Monaco' => 'Monaco',
					'Mongolia' => 'Mongolia',
					'Montenegro' => 'Montenegro',
					'Morocco' => 'Morocco',
					'Mozambique' => 'Mozambique',
					'Myanmar, {Burma}' => 'Myanmar, {Burma}',
					'Namibia' => 'Namibia',
					'Nauru' => 'Nauru',
					'Nepal' => 'Nepal',
					'Netherlands' => 'Netherlands',
					'New Zealand' => 'New Zealand',
					'Nicaragua' => 'Nicaragua',
					'Niger' => 'Niger',
					'Nigeria' => 'Nigeria',
					'Norway' => 'Norway',
					'Oman' => 'Oman',
					'Pakistan' => 'Pakistan',
					'Palau' => 'Palau',
					'Panama' => 'Panama',
					'Papua New Guinea' => 'Papua New Guinea',
					'Paraguay' => 'Paraguay',
					'Peru' => 'Peru',
					'Philippines' => 'Philippines',
					'Poland' => 'Poland',
					'Portugal' => 'Portugal',
					'Qatar' => 'Qatar',
					'Romania' => 'Romania',
					'Russian Federation' => 'Russian Federation',
					'Rwanda' => 'Rwanda',
					'St Kitts & Nevis' => 'St Kitts & Nevis',
					'St Lucia' => 'St Lucia',
					'Saint Vincent & the Grenadines' => 'Saint Vincent & the Grenadines',
					'Samoa' => 'Samoa',
					'San Marino' => 'San Marino',
					'Sao Tome & Principe' => 'Sao Tome & Principe',
					'Saudi Arabia' => 'Saudi Arabia',
					'Senegal' => 'Senegal',
					'Serbia' => 'Serbia',
					'Seychelles' => 'Seychelles',
					'Sierra Leone' => 'Sierra Leone',
					'Singapore' => 'Singapore',
					'Slovakia' => 'Slovakia',
					'Slovenia' => 'Slovenia',
					'Solomon Islands' => 'Solomon Islands',
					'Somalia' => 'Somalia',
					'South Africa' => 'South Africa',
					'South Sudan' => 'South Sudan',
					'Spain' => 'Spain',
					'Sri Lanka' => 'Sri Lanka',
					'Sudan' => 'Sudan',
					'Suriname' => 'Suriname',
					'Swaziland' => 'Swaziland',
					'Sweden' => 'Sweden',
					'Switzerland' => 'Switzerland',
					'Syria' => 'Syria',
					'Taiwan' => 'Taiwan',
					'Tajikistan' => 'Tajikistan',
					'Tanzania' => 'Tanzania',
					'Thailand' => 'Thailand',
					'Togo' => 'Togo',
					'Tonga' => 'Tonga',
					'Trinidad & Tobago' => 'Trinidad & Tobago',
					'Tunisia' => 'Tunisia',
					'Turkey' => 'Turkey',
					'Turkmenistan' => 'Turkmenistan',
					'Tuvalu' => 'Tuvalu',
					'Uganda' => 'Uganda',
					'Ukraine' => 'Ukraine',
					'United Arab Emirates' => 'United Arab Emirates',
					'United Kingdom' => 'United Kingdom',
					'United States' => 'United States',
					'Uruguay' => 'Uruguay',
					'Uzbekistan' => 'Uzbekistan',
					'Vanuatu' => 'Vanuatu',
					'Vatican City' => 'Vatican City',
					'Venezuela' => 'Venezuela',
					'Vietnam' => 'Vietnam',
					'Yemen' => 'Yemen',
					'Zambia' => 'Zambia',
					'Zimbabwe' => 'Zimbabwe',
				),
				'default_value' => 'United States',
				'return_format' => 'value',
				'multiple' => 0,
				'allow_null' => 0,
				'ui' => 0,
				'ajax' => 0,
				'placeholder' => '',
			),
			array(
				'key' => 'field_647f50ceac959',
				'label' => 'City',
				'name' => 'city',
				'aria-label' => '',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '33',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'maxlength' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
			),
			array(
				'key' => 'field_647f50d8ac95a',
				'label' => 'State',
				'name' => 'state',
				'aria-label' => '',
				'type' => 'select',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_647f5136ac95b',
							'operator' => '==',
							'value' => 'United States',
						),
					),
				),
				'wrapper' => array(
					'width' => '33',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'Alabama' => 'Alabama',
					'Alaska' => 'Alaska',
					'American Samoa' => 'American Samoa',
					'Arizona' => 'Arizona',
					'Arkansas' => 'Arkansas',
					'California' => 'California',
					'Colorado' => 'Colorado',
					'Connecticut' => 'Connecticut',
					'Delaware' => 'Delaware',
					'District of Columbia' => 'District of Columbia',
					'Florida' => 'Florida',
					'Georgia' => 'Georgia',
					'Guam' => 'Guam',
					'Hawaii' => 'Hawaii',
					'Idaho' => 'Idaho',
					'Illinois' => 'Illinois',
					'Indiana' => 'Indiana',
					'Iowa' => 'Iowa',
					'Kansas' => 'Kansas',
					'Kentucky' => 'Kentucky',
					'Louisiana' => 'Louisiana',
					'Maine' => 'Maine',
					'Maryland' => 'Maryland',
					'Massachusetts' => 'Massachusetts',
					'Michigan' => 'Michigan',
					'Minnesota' => 'Minnesota',
					'Mississippi' => 'Mississippi',
					'Missouri' => 'Missouri',
					'Montana' => 'Montana',
					'Nebraska' => 'Nebraska',
					'Nevada' => 'Nevada',
					'New Hampshire' => 'New Hampshire',
					'New Jersey' => 'New Jersey',
					'New Mexico' => 'New Mexico',
					'New York' => 'New York',
					'North Carolina' => 'North Carolina',
					'North Dakota' => 'North Dakota',
					'Northern Mariana Islands' => 'Northern Mariana Islands',
					'Ohio' => 'Ohio',
					'Oklahoma' => 'Oklahoma',
					'Oregon' => 'Oregon',
					'Pennsylvania' => 'Pennsylvania',
					'Puerto Rico' => 'Puerto Rico',
					'Rhode Island' => 'Rhode Island',
					'South Carolina' => 'South Carolina',
					'South Dakota' => 'South Dakota',
					'Tennessee' => 'Tennessee',
					'Texas' => 'Texas',
					'U.S. Virgin Islands' => 'U.S. Virgin Islands',
					'Utah' => 'Utah',
					'Vermont' => 'Vermont',
					'Virginia' => 'Virginia',
					'Washington' => 'Washington',
					'West Virginia' => 'West Virginia',
					'Wisconsin' => 'Wisconsin',
					'Wyoming' => 'Wyoming',
				),
				'default_value' => false,
				'return_format' => 'value',
				'multiple' => 0,
				'allow_null' => 0,
				'ui' => 0,
				'ajax' => 0,
				'placeholder' => '',
			),
			array(
				'key' => 'field_647f52419d4bb',
				'label' => 'Postal Code',
				'name' => 'postal_code',
				'aria-label' => '',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '33',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'maxlength' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
			),
			array(
				'key' => 'field_647f52669d4bc',
				'label' => 'Phone Number',
				'name' => 'phone_number',
				'aria-label' => '',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'maxlength' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
			),
			array(
				'key' => 'field_647f52769d4bd',
				'label' => 'Email Address',
				'name' => 'email_address',
				'aria-label' => '',
				'type' => 'email',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
			),
			array(
				'key' => 'field_647f52839d4be',
				'label' => 'Website',
				'name' => 'website',
				'aria-label' => '',
				'type' => 'url',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
			),
			array(
				'key' => 'field_647f6b46af0bf',
				'label' => 'Latitude',
				'name' => 'latitude',
				'aria-label' => '',
				'type' => 'number',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '50',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'min' => '',
				'max' => '',
				'placeholder' => '',
				'step' => '',
				'prepend' => '',
				'append' => '',
			),
			array(
				'key' => 'field_647f6b5eaf0c0',
				'label' => 'Longitude',
				'name' => 'longitude',
				'aria-label' => '',
				'type' => 'number',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '50',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'min' => '',
				'max' => '',
				'placeholder' => '',
				'step' => '',
				'prepend' => '',
				'append' => '',
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'store',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'acf_after_title',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => array(
			0 => 'the_content',
			1 => 'excerpt',
			2 => 'discussion',
			3 => 'comments',
			4 => 'slug',
			5 => 'format',
			6 => 'categories',
			7 => 'tags',
			8 => 'send-trackbacks',
		),
		'active' => true,
		'description' => '',
		'show_in_rest' => 0,
	) );
} );

